//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RidesVp
    {
        public int RideId { get; set; }
        public string RideName { get; set; }
        public string Image { get; set; }
        public int NumberSeets { get; set; }
        public System.TimeSpan DuringUsing { get; set; }
        public int AgeUser { get; set;}
        public int Mone { get; set; }

        public int NumMinutes { get; set; }

        public System.DateTime CurrentTime { get; set; }
    }
}
