//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandBy
    {
        public int UserId { get; set; }
        public int RideId { get; set; }
        public int NumberTimings { get; set; }
        public int StandById { get; set; }
    
        public virtual Rides Rides { get; set; }
        public virtual Users Users { get; set; }
    }
}
