//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Ride
    {
        public int rideId { get; set; }
        public int userId { get; set; }
        public Nullable<System.TimeSpan> currentTime { get; set; }
        public Nullable<System.TimeSpan> timeVp { get; set; }
    }
}
